force-app/main/default/objects/Account/fields/OpenInquiriesCount__c.field-meta.xml
<CustomField>
    <fullName>OpenInquiriesCount__c</fullName>
    <label>Open Inquiries Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Open_Inquiry__c/Open_Inquiry__c.object-meta.xml
<CustomObject>
    <label>Open Inquiry</label>
    <nameField>
        <label>Open Inquire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Inquiries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Open_Inquiry__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Open Inquiries</relationshipLabel>
    <relationshipName>Open_Inquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/triggerhandlers/OpenInquiryHandler.cls
public with sharing class OpenInquiryHandler {

    public static void calculateOpenInquiryHandler( Set<Id> parentIds) {

        List<Account> parentsToUpdate = AccountSelector.getAccounts(parentIds);
    
        for (Account parent : parentsToUpdate) {
            Integer childRecordCount = parent.Open_Inquiries__r.size();
    
            parent.OpenInquiriesCount__c = childRecordCount;
        }
    
        update parentsToUpdate;
    }
}